const { __ } = wp.i18n;
export const animationslist=[
	{ label: __('None','gutensee'), value: ' ' },
    { label: __('Bounce','gutensee'), value: 'bounce' },
    { label: __('Flash','gutensee'), value: 'flash' },
    { label: __('Pulse','gutensee'), value: 'pulse' },
    { label: __('RubberBand','gutensee'), value: 'rubberBand' },
    { label: __('Shake','gutensee'), value: 'shake' },
    { label: __('Swing','gutensee'), value: 'swing' },
    { label: __('Tada','gutensee'), value: 'tada' },
    { label: __('Wobble','gutensee'), value: 'wobble' },
    { label: __('Jello','gutensee'), value: 'jello' },
    { label: __('BounceIn','gutensee'), value: 'bounceIn' },
    { label: __('BounceInDown','gutensee'), value: 'bounceInDown' },
    { label: __('BounceInLeft','gutensee'), value: 'bounceInLeft' },
    { label: __('BounceInRight','gutensee'), value: 'bounceInRight' },
    { label: __('BounceInUp','gutensee'), value: 'bounceInUp' },
    { label: __('FadeIn','gutensee'), value: 'fadeIn' },
    { label: __('FadeInDown','gutensee'), value: 'fadeInDown' },
    { label: __('FadeInDownBig','gutensee'), value: 'fadeInDownBig' },
    { label: __('FadeInLeft','gutensee'), value: 'fadeInLeft' },
    { label: __('FadeInLeftBig','gutensee'), value: 'fadeInLeftBig' },
    { label: __('FadeInRight','gutensee'), value: 'fadeInRight' },
    { label: __('FadeInRightBig','gutensee'), value: 'fadeInRightBig' },
    { label: __('FadeInUp','gutensee'), value: 'fadeInUp' },
    { label: __('FadeInUpBig','gutensee'), value: 'fadeInUpBig' },
    { label: __('Flip','gutensee'), value: 'flip' },
    { label: __('FlipInX','gutensee'), value: 'flipInX' },
    { label: __('FlipInY','gutensee'), value: 'flipInY' },
    { label: __('LightSpeedIn','gutensee'), value: 'lightSpeedIn' },
    { label: __('RollIn','gutensee'), value: 'rollIn' },
    { label: __('RotateIn','gutensee'), value: 'rotateIn' },
    { label: __('RotateInDownLeft','gutensee'), value: 'rotateInDownLeft' },
    { label: __('RotateInDownRight','gutensee'), value: 'rotateInDownRight' },
    { label: __('RotateInUpLeft','gutensee'), value: 'rotateInUpLeft' },
    { label: __('RotateInUpRight','gutensee'), value: 'rotateInUpRight' },
    { label: __('SlideInDown','gutensee'), value: 'slideInDown' },
    { label: __('SlideInLeft','gutensee'), value: 'slideInLeft' },
    { label: __('SlideInRight','gutensee'), value: 'slideInRight' },
    { label: __('ZoomIn','gutensee'), value: 'zoomIn' },
    { label: __('ZoomInDown','gutensee'), value: 'zoomInDown' },
    { label: __('ZoomInLeft','gutensee'), value: 'zoomInLeft' },
    { label: __('ZoomInRight','gutensee'), value: 'zoomInRight' },
    { label: __('ZoomInUp','gutensee'), value: 'zoomInUp' },
] 
export const animationsdurations=[
	{ label: __('Normal','gutensee'), value: ' ' },
    { label: __('Slow','gutensee'), value: 'slow' },
    { label: __('Fast','gutensee'), value: 'fast' },
] 